// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAITJM3ySdz1-4yBxozm8YeQ06OjqBspKI',
    appId: '1:884611629753:web:d8c3ede0494857791f1168',
    messagingSenderId: '884611629753',
    projectId: 'msf2026-dfd1c',
    authDomain: 'msf2026-dfd1c.firebaseapp.com',
    storageBucket: 'msf2026-dfd1c.firebasestorage.app',
    measurementId: 'G-CCQ5HV3CSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwC8XYOKf8tx4zcbYrIcxx1G0hYEJ6-RM',
    appId: '1:884611629753:android:9a6b54752908f2d01f1168',
    messagingSenderId: '884611629753',
    projectId: 'msf2026-dfd1c',
    storageBucket: 'msf2026-dfd1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwqhfh6WosKk21hpoDlcJ30bI4rxbHZa0',
    appId: '1:884611629753:ios:7aec0100c76f45191f1168',
    messagingSenderId: '884611629753',
    projectId: 'msf2026-dfd1c',
    storageBucket: 'msf2026-dfd1c.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwqhfh6WosKk21hpoDlcJ30bI4rxbHZa0',
    appId: '1:884611629753:ios:7aec0100c76f45191f1168',
    messagingSenderId: '884611629753',
    projectId: 'msf2026-dfd1c',
    storageBucket: 'msf2026-dfd1c.firebasestorage.app',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAITJM3ySdz1-4yBxozm8YeQ06OjqBspKI',
    appId: '1:884611629753:web:c4b3ce3b3c320dfa1f1168',
    messagingSenderId: '884611629753',
    projectId: 'msf2026-dfd1c',
    authDomain: 'msf2026-dfd1c.firebaseapp.com',
    storageBucket: 'msf2026-dfd1c.firebasestorage.app',
    measurementId: 'G-6SZQQDKF6V',
  );
}
